# Site settings
title: CalcYu's Personal Website
email: hi@geek5.cn
description: > # this means to ignore newlines until "baseurl:"
  Geek5是极客武馆的意思，是求愚（CalcYu）的个人网站，学习软件研发技术好比学习武术一样需要耐心和毅力以及极客精神。
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://geek5.cn # the base hostname & protocol for your site
rss_url: /feed.xml
author: CalcYu
img_url: /assets/images/

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
github: calcyu
linkedin: calcyu


# avatar and Favicon
logo: /assets/img/geek5_86x86.png
favicon: /favicon.ico

# vssue config
vssue:
  owner: calcyu
  repo: calcyu.github.io
  client_id: 1942b8ee3553f7f75089
  client_secret: 3e42319bb0502146994d770c4d2851bb4f3e44b6
  labels: Geek5.cn
  prefix: comment

# google analytics config
# ga:
#   id: UA-87935934-1
#   url: geek5.cn

# Build settings
permalink: /blog/:year/:month/:day/:title.html
paginate_path: "/blog/page:num/"
paginate: 10
# excerpt
excerpt_separator: "\n\n"
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-algolia

#default value
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: _posts/tool
  values:
    layout: post
    categories: '工具'
- scope:
    path: _posts/book
  values:
    layout: post
    categories: '读书'
- scope:
    path: _posts/life
  values:
    layout: post
    categories: '生活'
- scope:
    path: _posts/resource
  values:
    layout: post
    categories: '资源'
- scope:
    path: _posts/front
  values:
    layout: post
    categories: '前端'
- scope:
    path: _posts/end
  values:
    layout: post
    categories: '后端'
- scope:
    path: _posts/tech
  values:
    layout: post
    categories: '技术'

#algolia
algolia:
  application_id: 'Z8F4DOSV5P'
  index_name:     'geek5'
