---
name: Geek5
creator: CalcYu
description: Software engineer obsessed with Web technologies
url: http://geek5.cn
baseurl:
permalink: "/blog/:year/:month/:day/:title.html"
paginate_path: "/blog/page:num/"
paginate: 10

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: blog
    type: pages
  values:
    sectionid: blog

exclude:
- Gemfile
- Gemfile.lock
- README.md

markdown:    kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

sass:
  style: :compressed
  sass_dir: _css

plugins:
- jekyll-redirect-from
- jekyll-paginate

excerpt_separator: "\n\n"

# Social
social:
  weibo: e73g
  github: calcyu
  twitter: calcyu
  mail: hi@geek5.cn