---
name: Geek5
description: Software engineer obsessed with Web technologies
url: http://geek5.cn
baseurl:
permalink: "/blog/:year/:month/:day/:title.html"
paginate_path: "/blog/page:num/"
paginate: 10

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: blog
    type: pages
  values:
    sectionid: blog

exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle

markdown:    kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

sass:
  style: :compressed
  sass_dir: _css

plugins:
- jekyll-redirect-from
- jekyll-paginate

excerpt_separator: "\n\n"

algolia:
  application_id: 'Z8F4DOSV5P'
  index_name:     'geek5'
#algolia update command
#bundle exec jekyll algolia
